# Generated by Django 4.0.5 on 2022-06-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_authoradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorAdmin',
        ),
    ]
